### PR TITLE
network extensions ggnet and ggnetwork

### PR DESCRIPTION
**Pull request by briatte**
Also contains cross links between the four (!) different ggplot2 extensions that bring network visualisation to ggplot2.

### CODE REVIEW

**Comment by briatte** [comment]
Wait, something's wrong.

**Comment by briatte** [comment]
Crap, I have no idea how to ask to merge this with the `dev` branch instead of the `master` one… Sorry for the mess.

**Comment by Emaasit** [comment]
Don't worry. Let me created the Rmd files and you can make any additions later.

**Comment by briatte** [comment]
Thanks!

**Pull request closed without merging**
